routes/web.php
<?php

use App\Notifications\SomeNotifications;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::post("/notifications/all", "NotificationsController@subscribeAll");
Route::get("/notifications/question/{id}", "NotificationsController@sendReply");
//Route::get("/notifications/test", "NotificationsController@sendReply");

Route::get('/', 'HomeController@index');
//Route::get('/filter/{id}', 'HomeController@index');

Route::get('questions/user', 'QuestionController@user')->name('questions.user');
Route::get('profil/user', 'HomeController@profil')->name('profil.user');
Route::post('profil/edit', 'HomeController@editProfil')->name('profil.editProfil');


Route::resource('questions', 'QuestionController')->only([
    'index', 'create', 'store', 'show'
]);

Route::resource('answers', 'AnswerController')->only([
    'store'
]);

Route::post('upvotes/select', 'UpvoteController@select');
Route::resource('upvotes', 'UpvoteController')->only([
    'store'
]);

Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );

Route::get('/admin/users',  'AdminController@users')->name('admin.users' );
Route::get('/admin/users/{id}/login',  'AdminController@userLogin')->name('admin.user.login' );
Route::get('/admin/users/{id}/delete',  'AdminController@userDelete')->name('admin.user.delete' );

Route::post('/delete_question', 'AdminController@deleteQuestion')->name('deleteQuestion');
Route::post('/delete_answer', 'AdminController@deleteAnswer')->name('deleteAnswer');
Route::post('/question/edit', 'AdminController@editQuestion')->name('questionEdit');
Route::post('/question/edit/update', 'AdminController@updateQuestion')->name('questionUpdate');
Route::post('/question/lock', 'AdminController@lockQuestion')->name('questionLock');

resources/views/partials/firebase-js.blade.php
<script src="https://www.gstatic.com/firebasejs/5.8.3/firebase.js"></script>
{{-- <script src="https://www.gstatic.com/firebasejs/5.8.2/firebase-messaging.js"></script> --}}

<script>
    // Initialize Firebase
    var config = {
        apiKey: "AIzaSyDXabp3SlbYwZNJWkOEFwR8Y-k4jtAanoM",
        authDomain: "exchange-54a3c.firebaseapp.com",
        databaseURL: "https://exchange-54a3c.firebaseio.com",
        projectId: "exchange-54a3c",
        storageBucket: "exchange-54a3c.appspot.com",
        messagingSenderId: "1026872785103"
    };
    firebase.initializeApp(config);
</script>
<script>

    // Retrieve Firebase Messaging object.
    const messaging = firebase.messaging();

    // Add the public key generated from the console here.
    messaging.usePublicVapidKey("BEEDl4ugMHIFfYCCwONFgM8lJyVP6uyacyxSmB7-2EW_DXG7LfeKSzRVFD4qty5LD6ktvXqszhsWk3MjdKILhrE");

    function enableNotifications(params) {

        let checkboxNotification = document.getElementById('checkboxNotification');

        if(checkboxNotification.checked) {

            messaging.requestPermission().then(function () {
                console.log('Notification permission granted.');
                // TODO(developer): Retrieve an Instance ID token for use with FCM.

                // Get Instance ID token. Initially this makes a network call, once retrieved
                // subsequent calls to getToken will return from cache.
                messaging.getToken().then(function (currentToken) {
                    if (currentToken) {
                        console.log(currentToken, params);
                        sendTokenToServer(currentToken, params);
                    } else {
                        // Show permission request.
                        console.log('No Instance ID token available. Request permission to generate one.');
                    }
                }).catch(function (err) {
                    console.log('An error occurred while retrieving token. ', err);
                });

            }).catch(function (err) {
                console.log('Unable to get permission to notify.', err);
            });




            // Callback fired if Instance ID token is updated.
            messaging.onTokenRefresh(function () {
                messaging.getToken().then(function (refreshedToken) {
                    console.log('Token refreshed.');

                    // Send Instance ID token to app server.
                    sendTokenToServer(refreshedToken, params);
                    // ...
                }).catch(function (err) {
                    console.log('Unable to retrieve refreshed token ', err);
                });
            });
            // Handle incoming messages. Called when:
            // - a message is received while the app has focus
            // - the user clicks on an app notification created by a service worker
            //   `messaging.setBackgroundMessageHandler` handler.
            messaging.onMessage(function (payload) {
                console.log('Message received. ', payload);
                // ...
            });

        } else {
            let inputToken = document.getElementById('token');

            if(inputToken) {
                inputToken.parentNode.removeChild(inputToken);
                console.log('input token remove');
            }
        }

    }

    function sendTokenToServer(token, params) {

        const tokenInputString = '<input type="hidden" id="token" name="token_firebase" value="'+token+'">';

        if(params.type === "all") {
            $('#registerForm').append(tokenInputString);
        }
        else if (params.type === "question") {
             $('#registerForm').append(tokenInputString);
        } else {

            fetch('/notifications/question/'+params.question_id, {
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                },
                method: "POST",
                body: JSON.stringify({token_firebase: token })
            }).then(function (response) {
                return response.json();
            }).then(function (json) {
                if(json.is_subscribed === 1) {
                    console.log("User has been subscribed to notifications.")
                }
                else {
                    console.log("Error while subscribing user to notifications. "+token)
                }
            });
        }
    }

</script>

resources/views/partials/footer.blade.php
<footer id="footer">
    <section class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="widget widget_contact">
                    <h3 class="widget_title colorTextSimplon">Exchange ?</h3>
                    <p>Un lieu d'échange convivial où toutes questions trouvera une réponse</p>
                    <p>Apprentissage de la pédagogie de l'entraide. Savoir questionner pour obtenir des réponses pertinentes</p>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="widget">
                    <h3 class="widget_title colorTextSimplon">Liens utiles</h3>
                    <ul>
                        <li class="{{ Request::is('/') ? 'current_page_item' : '' }}">
                            <a href="{{ url('/') }}">Accueil</a>
                        </li>
                        <li class="{{ Request::is('questions/create') ? 'current_page_item' : '' }}">
                            @if (Auth::guest())
                                <a href="{{ url('/login') }}">Poser une question</a>
                            @else
                                <a href="{{ url('/questions/create') }}">Poser une question</a>
                            @endif
                        </li>
                        <li class="">
                            <a href="{{ route('questions.index') }}">Aider la communauté</a>
                        </li>
                        <li class="">
                            <a href="#!">Foire Aux Questions</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 text-right">
                    <div class="widget widget_contact">
                        <h3 class="widget_title colorTextSimplon">Intéret ?</h3>
                        <p>Créer en tant que projet back office pour la fabrique de Roanne, cette outil à vocation pédagogique a pour objectif de servir de lieu d'échange entre tous simploniens de toutes promotions.</p>
                    </div>
                </div>
            </div>
        </div><!-- End row -->
    </section><!-- End container -->
</footer><!-- End footer -->
<footer id="footer-bottom">
    <section class="container-fluid">
        <div class="copyrights f_left">Copyright 2019 Une Question ? | <a href="mailto:contact@idmkr.io">By Simplon-Roanne</a></div>
        <div class="social_icons f_right">
            <span class="facebook"><a original-title="Facebook" class="tooltip-n" href="https://fr-fr.facebook.com/SimplonRoanne/"><i class="social_icon-facebook font17"></i></a></span>
            <span class="twitter"><a original-title="Twitter" class="tooltip-n" href="#!"><i class="social_icon-twitter font17"></i></a></span>
        </div><!-- End social_icons -->
    </section><!-- End container -->
</footer><!-- End footer-bottom -->

resources/views/partials/head.blade.php
<!-- Basic Page Needs -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="Exchange Simplon.co – Questions/réponses pour les promotions Simplon">
<meta name="author" content="Idmkr">

<!-- Bootstrap 4 -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<link rel="stylesheet" href="{{ asset('/css/simplon-style.css') }}">

{{-- <!-- Mobile Specific Metas --> --}}
{{-- <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- Main Style -->
<link href="{{ asset('/css/style.css') }}" rel="stylesheet">

<!-- Skins -->
<link href="{{ asset('/css/skins/skins.css') }}" rel="stylesheet">

<!-- Responsive Style -->
<link href="{{ asset('/css/responsive.css') }}" rel="stylesheet">

<!-- Favicons -->
<link rel="shortcut icon" href="public/images/favicon.png"> --}}

{{-- <style>
	code {
        background: #eee;
	    padding: 2px 5px;
	}


</style> --}}

@yield('styles')

resources/views/partials/header.blade.php
<div id="header-top" class="colorBackgroundSimplon">
    <section class="container-fluid clearfix">
        <nav class="header-top-left-nav">
            <ul>
                @if($currentUser)
                    <li>Bonjour {{ $currentUser->name }}. Tu as {{ $currentUser->points }} points de karma</li>
                @else
                    <li>Hey Simplonnien.ne ! Rejoins-nous vite =></li>
                @endif
            </ul>
        </nav>
        <div class="header-top-right">
            @if($currentUser)
                <div class="dropdown">
                    <button class="btn btn-small btn-profil dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Mon profil
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{{ route('profil.user') }}">Mes informations</a>
                        @if($currentUser->is_admin)
                            <a class="dropdown-item" href="{{ route('admin.users') }}">Administrateur</a>
                            <div class="dropdown-divider"></div>
                        @endif
                        <a class="dropdown-item" href="{{ url('/logout') }}">Déconnexion</a>
                    </div>
                </div>
            @else
                <nav class="header-top-right-nav">
                    <ul>
                        <li><a href="{{ url('/login') }}">Connexion</a></li>
                        <li><a href="{{ url('/register') }}">Inscription</a></li>
                    </ul>
                </nav>
            @endif
        </div>
    </section><!-- End container -->
</div>
<header id="header">
    <!-- navbar bootstrap -->
    <nav class="navbar navbar-expand-lg navbar-dark ">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url('/') }}">
                <span class="colorTextSimplon text-wrap">Simplon-Exchange</span>.Help
            </a><span class="badge badge-light beta">Béta</span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {{ Request::is('/') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ url('/') }}">Accueil <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {{ Request::is('questions/create') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ route('questions.create') }}">Poser une question</a>
                    </li>
                    <li class="nav-item {{ Request::is('questions') ? 'active' : '' }}">
                        <a class="nav-link" href="{{ route('questions.index') }}">Donner une réponse</a>
                    </li>
                    <li class="nav-item last {{ Request::is('faq') ? 'active' : '' }}">
                        <a class="nav-link" href="#">Foire aux questions</a>
                    </li>
                    <div class="mobile-nav">
                        @if($currentUser)
                            <div class="dropdown-divider"></div>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('profil.user') }}">Profil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin.users') }}">Administrateur</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url('/logout') }}">Déconnexion</a>
                            </li>
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url('/login') }}">Connexion</a>
                            </li>
                        @endif
                    </div>
                </ul>
            </div>
        </div>
    </nav>
</header><!-- End header -->

resources/views/partials/messages.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-block">
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-block">
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        Please check the form below for error
    </div>
@endif

resources/views/partials/question.blade.php
<div class="card mt-3 shadow-sm">
    <div class="card-body">
        <a class="card-link title-card colorTextSimplon" href="{{ url('/questions/'.$question->id) }}">{{ $question->title }}</a>
        <div class="btn-block-admin">
            @if(Auth::check() && Auth::user()->is_admin == 1 && Auth::user()->fabric_id == $question->user->fabric_id)
                <form method="POST" action="{{ route('questionEdit') }}" class="btn-admin ">
                    {{ csrf_field() }}
                    <input type="hidden" value="{{$question->id}}" name="questionId">
                    <button class="btn" type="submit" data-toggle="tooltip" data-placement="top" title="Editer"><i class="fas fa-edit"></i></button>
                </form>
            @endif

            @if(Auth::check() && Auth::user()->is_admin == 1 && Auth::user()->fabric_id == $question->user->fabric_id)
                <form method="POST" action="{{ route('deleteQuestion') }}" class="btn-admin mx-2">
                    {{ csrf_field() }}
                    <input type="hidden" value="{{$question->id}}" name="questionId">
                    <button class="btn" type="submit" data-toggle="tooltip" data-placement="top" title="Supprimer"
                            onclick="return confirm('Confirmer la suppression ?')">
                        <i class="fas fa-trash"></i>
                    </button>
                </form>
            @endif

            @if (Auth::check() && Auth::user()->is_admin == 1 && !$question->is_locked )
                    <form method="post" action="{{ route('questionLock') }}" class="btn-admin">
                        {{ csrf_field() }}
                        <input type="hidden" name="question_id" value="{{ $question->id }}">
                        <button type="submit" id="submit" class="btn" data-toggle="tooltip" data-placement="top" title="Fermer la question">
                            <i class="fas fa-times"></i>
                        </button>
                    </form>
                {{--<div class="btn-admin">
                    {!! Form::open(['action' => 'AdminController@lockQuestion', 'method' => 'post']) !!}
                    {!! Form::hidden('question_id', $question->id) !!}
                    {!! Form::submit('Fermer cette question', ['id' => 'submit', 'class' => 'btn']) !!}
                    {!! Form::close() !!}
                </div>--}}
                <hr>
            @endif
        </div>



        <div class="card-subtitle mb-2 mt-2 text-muted clearfix">
            <em>{{ $question->created_at->diffForHumans() }}</em> par <span class="color">{{ $question->user->name }}</span>
        </div>

        <hr>

        <div class="d-inline-flex flex-column align-middle">
            @if(in_array($question->id, $userQuestionPreviousVotes))
                <li class="list-unstyled mb-1">
                    <input type="submit" value="▲"
                        class="upVoted"
                        title='Vous avez déjà upvoté cette question'>
                </li>
            @else
                <li class="list-unstyled mb-1">
                    {!! Form::open(['action' => 'UpvoteController@store', 'method' => 'post']) !!}
                    {!! Form::hidden('question_id', $question->id) !!}
                    {!! Form::submit('▲', ['class' => 'question-vote-up']) !!}
                    {!! Form::close() !!}
                </li>
            @endif

            <div class="text-center nbVotes">
                {{count($question->upvotes)}}
            </div>
        </div>
        <div class="card-text d-inline-block col-11 align-middle mt-2">
            {!! strip_tags($question->description, '<a><b><blockquote><code><del><dd><dl><dt><em><h1><h2><h3><i><kbd><li><ol><p><pre><s><sup><sub><strong><strike><ul><br><hr>') !!}
        </div>
        <hr>
        <div class="clearfix link-card">
                <a href="/questions/{{$question->id}}" class="card-link "><i class="fas fa-comment"></i> {{ count($question->answers) }} Réponse(s)</a>
                <span class="ml-3"><i class="far fa-eye"></i> {{ $question->views }} vues </span>
                @if($question->hasSelectedAnswer)
                    <span class="ml-3"><i class="fas fa-check"></i> Solution trouvée</span>
                @endif
                <span class="ml-3 colorBackgroundSimplon fabric-span">{{ $question->user->fabric->name }}</span>

                <a href="/?category={{ $question->category }}" class="float-right card-link ml-3"><i class="fas fa-tags"></i> {{ $question->category }}</a>
                <div class="clearfix"></div>
        </div>
    </div>
</div>

resources/views/partials/recent-questions.blade.php
<div class="card activite-recent shadow-sm">
    <div class="card-body">
        <h5 class="card-title colorTextSimplon">Activité récente</h5>
        @forelse($recentQuestions as $recentQuestion)
            <hr>
            <h6 class="card-subtitle mt-3 mb-2">
                <a href="{{ route('questions.show', ['id' => $recentQuestion->id]) }}">{{ $recentQuestion->title }}</a>
            </h6>
            <p class="card-text text-muted">{{ str_limit(strip_tags($recentQuestion->description), 120) }}</p>
            <p class="card-text"><small class="text-muted">{{ $recentQuestion->created_at }}</small></p>
            
        @empty
            <p>Pas de questions posés.</p>
        @endforelse
    </div>
</div>

resources/views/partials/search.blade.php
<div id="search" class="colorBackgroundSimplon">
    <div class="container-fluid searchBar">
        <div class="row">
            <div class="col-md-12">
                @if (!Auth::check())
                <div class="text-center">
                    <h2 class="my-5">Bienvenue sur Simplon-Exchange.Help</h2>
                    <p class="pb-3">
                        Tous les Simplonnien.ne.s débutant.e.s font face aux mêmes problèmes/bogues/erreurs, mais n'osent pas toujours demander ou ne trouvent pas toujours les bonnes réponses.
                        <br>Sois rassuré.e, ici tu es libre de poser la question que tu veux, une réponse fiable et de confiance te sera faite par un.e autre apprenant.e, un.e ancien.ne Simplonien.ne ou un formateur.
                        <br><b>N'attend plus, pose ta question dès maintenant !</b>
                    </p>
                </div>
                @endif

                <form method="get" class="mt-5 mb-5">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text label" id="basic-addon1"><i class="fas fa-pencil-alt"></i></span>
                        </div>
                        <input type="text" class="form-control" name="search" aria-label="Username" aria-describedby="basic-addon1" value="Recherche une question, tu es sur de trouver une réponse." onfocus="if(this.value=='Recherche une question, tu es sur de trouver une réponse.')this.value='';" onblur="if(this.value=='')this.value='Recherche une question, tu es sur de trouver une réponse.';">
                        <div class="input-group-append">
                            <button class="btn btn-custom colorBackgroundSimplon" type="submit" id="button-addon2">Rechercher</button>
                        </div>
                    </div>
                    {{-- <div class="input-group input-group-lg">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1"><i class="fas fa-pencil-alt"></i></span>
                        </div>
                        <input type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1" value="Recherche une question, tu es sur de trouver une réponse." onfocus="if(this.value=='Recherche une question, tu es sur de trouver une réponse.')this.value='';" onblur="if(this.value=='')this.value='Recherche une question, tu es sur de trouver une réponse.';">
                    </div> --}}
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/partials/sidebar.blade.php
<div class="card mt-4 shadow-sm stats">
    <div class="card-body">
        <h5 class="card-title colorTextSimplon">Stats</h5>
        <hr>
        <p class="card-text text-center">
            <i class="far fa-question-circle"></i> 
            Questions ({{ isset($questionsCount) ? $questionsCount : \App\Question::count() }})
        </p>
        <p class="card-text text-center">
            <i class="far fa-comment "></i> 
            Réponses ({{ isset($answersCount) ? $answersCount : \App\Answer::count() }})
        </p>
    </div>
</div>

<!--
<div class="widget widget_tag_cloud">
    <h3 class="widget_title">Tags</h3>
    <a href="#">projects</a>
    <a href="#">Portfolio</a>
    <a href="#">Wordpress</a>
    <a href="#">Html</a>
    <a href="#">Css</a>
    <a href="#">jQuery</a>
    <a href="#">2code</a>
    <a href="#">vbegy</a>
</div>
!-->